cacheFolder: .yarn

injectEnvironmentFiles:
  - .env?
  - .env.local?
  - .env.development?
  - .env.production?

nodeLinker: node-modules

# npmScopes:
#   duydpdev:
#     npmAlwaysAuth: true
#     npmAuthToken: "${CI_WORKER_REPOSITORY_TOKEN}"
#     npmPublishRegistry: "https://npm.pkg.github.com"
#     npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
