cacheFolder: .yarn

injectEnvironmentFiles:
  - .env?
  - .env.local?
  - .env.development?
  - .env.production?

nodeLinker: node-modules

npmScopes:
  duydpdev:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN-}"
    npmPublishRegistry: "https://registry.npmjs.org"
    npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
