cacheFolder: .yarn

injectEnvironmentFiles:
  - .env?
  - .env.local?
  - .env.development?
  - .env.production?

nodeLinker: node-modules

# npmScopes:
#   duydpdev:
#     npmAlwaysAuth: true
#     npmAuthToken: "${CI_WORKER_REPOSITORY_TOKEN}"
#     npmPublishRegistry: "${CI_SERVICE_REPOSITORY_NPM_PUBLIC_URL}"
#     npmRegistryServer: "${CI_SERVICE_REPOSITORY_NPM_PUBLIC_URL}"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
